language: android
android:
  components:
    - build-tools-23.0.0
    - android-22
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'
    - '.*intel.+'
install:
  - gradle build connectedCheck
script:
